version: 2.1


executors:
  my-executor:
    docker:
      - image: rust:latest
    working_directory: /tmp



jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: build
          command: cargo build --verbose -p nalgebra;
      - persist_to_workspace:
          root: .
          paths:
            - target
#      - run:
#          name: build arbitrary
#          command: cargo build --verbose -p nalgebra --features "arbitrary";
#      - run:
#          name: build mint
#          command: cargo build --verbose -p nalgebra --features "mint";
#      - run:
#          name: build alloc
#          command: cargo build --verbose -p nalgebra --features "alloc";
#      - run:
#          name: build serde-serialize
#          command: cargo build --verbose -p nalgebra --features "serde-serialize";
#      - run:
#          name: build abomonation-serialize
#          command: cargo build --verbose -p nalgebra --features "abomonation-serialize";
#      - run:
#          name: build debug
#          command: cargo build --verbose -p nalgebra --features "debug";
#      - run:
#          name: build all-features
#          command: cargo build --verbose -p nalgebra --all-features;
  test:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: test
          command: cargo test --verbose;
      - attach_to_workspace:
          at: target
#      - run:
#          name: test arbitrary
#          command: cargo test --verbose "arbitrary";
#      - run:
#          name: test all-features
#          command: cargo test --verbose --all-features;
#      - run:
#          name: test nalgebra-glm
#          command: cd nalgebra-glm; cargo test --verbose;

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
