version: 2
jobs:
  build:
    docker:
      - image: rust:latest

    steps:
      - checkout
      - run:
          name: Build all
          command: |
              cargo build --verbose -p nalgebra;
              cargo build --verbose -p nalgebra --features "arbitrary";
              cargo build --verbose -p nalgebra --features "mint";
              cargo build --verbose -p nalgebra --features "alloc";
              cargo build --verbose -p nalgebra --features "serde-serialize";
              cargo build --verbose -p nalgebra --features "abomonation-serialize";
              cargo build --verbose -p nalgebra --features "debug";
              cargo build --verbose -p nalgebra --all-features
              cargo test --verbose;
              cargo test --verbose "arbitrary";
              cargo test --verbose --all-features; 
              cd nalgebra-glm; cargo test --verbose;

      - run:
          name: Print the Current Time
          command: date